### PR TITLE
utilize 'fs' plugin

### PR DESCRIPTION
**Pull request by wmhilton**
image

### CODE REVIEW

**Comment by jcubic** [comment]
Wow, thank you for the PR will add you to contributors.js

**Comment by wmhilton** [comment]
I can help with the credentialManager API integration too if you're interested?

**Comment by jcubic** [comment]
I have it already implemented but I have one issue, I would like to pause the terminal while I execute command so I need somehow execute code after the plugin, did you consider implement complete callback function?

**Comment by jcubic** [comment]
Also this [isomorphic-git#400](https://github.com/isomorphic-git/isomorphic-git/issues/400)

**Comment by wmhilton** [comment]
Oh! Oooooohhhhhh. Oh. You're talking about the `approved` and `rejected` functions! Very good point. Hang on.

**Pull request merged**
